spring:
    application:
        name: user-service-ecram
    port: 30001

    datasource:
        initialization-mode: always
        username: postgres
        url: jdbc:postgresql://localhost:5432/ecram_security
        platform: postgres
        password: admin
    jpa:
        show-sql: true
        properties:
            hibernate:
                jdbc:
                    lob:
                        non_contextual_creation: 'true'
                format_sql: true
        hibernate:
            ddl-auto: update


eureka:
    instance:
        instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
